--[[
    Global constants
]]

WINDOW_WIDTH = 640
WINDOW_HEIGHT = 480

TILE_SIZE_X = 32
TILE_SIZE_Y = 32
MAX_TILES_X = WINDOW_WIDTH / TILE_SIZE_X
MAX_TILES_Y = WINDOW_WIDTH / TILE_SIZE_Y

TILE_EMPTY = 0
TILE_SNAKE_HEAD = 1
TILE_SNAKE_BODY = 2
TILE_APPLE = 3

SNAKE_SPEED = 120
SNAKE_SIZE_X = TILE_SIZE_X
SNAKE_SIZE_Y = TILE_SIZE_Y
