--[[
    Global constants
]]

WINDOW_WIDTH = 640
WINDOW_HEIGHT = 480

STATE_GAME_OVER = 0
STATE_PLAYING = 1

TILE_SIZE_X = 32
TILE_SIZE_Y = 32
MAX_TILES_X = WINDOW_WIDTH / TILE_SIZE_X
MAX_TILES_Y = WINDOW_HEIGHT / TILE_SIZE_Y

TILE_EMPTY = 0
TILE_SNAKE_HEAD = 1
TILE_SNAKE_BODY = 2
TILE_APPLE = 3

SNAKE_SPEED = 0.2 -- time in seconds that is needed per tile
SNAKE_SIZE_X = TILE_SIZE_X
SNAKE_SIZE_Y = TILE_SIZE_Y
SNAKE_IS_WRAPPING = false
